export const es = {
  "skip": "Saltar al espacio de trabajo",
  "navigation": "Navegación principal",
  "brandLabel": "Espacio de trabajo de Vision2Code",
  "capture": "Captura",
  "code": "Código",
  "projectsSoon": "Proyectos, próximamente",
  "projects": "Proyectos",
  "librarySoon": "Biblioteca, próximamente",
  "library": "Biblioteca",
  "footer": "Vision2Code / Estudio de interfaces",
  "version": "Versión 0.1.0",
  "captureEyebrow": "Generador / Consola 01",
  "captureTitle": "Consola de captura",
  "captureIntro": "De una referencia visual a una estructura de interfaz.",
  "analysisBadge": "Análisis de interfaces",
  "inputStage": "Entrada",
  "profileStage": "Perfil",
  "analysisStage": "Análisis",
  "resultStage": "Resultado",
  "exportStage": "Exportación",
  "workflow": "Etapas del flujo de trabajo",
  "soon": "Próximamente",
  "profileEyebrow": "Panel de configuración",
  "profileTitle": "Perfil de generación",
  "outputStack": "Tecnología de salida",
  "noFramework": "Sin framework",
  "styles": "Estilos",
  "language": "Idioma",
  "codeLanguage": "Lenguaje",
  "fidelity": "Fidelidad visual",
  "structure": "Estructura principal",
  "structureHelp": "Distribución, texto y controles.",
  "instructions": "Instrucciones · Próximamente",
  "instructionsHelp": "Las instrucciones de generación estarán disponibles en una próxima etapa.",
  "profileHelp": "El análisis utiliza solo tu captura. La generación de código está disponible para React + Tailwind CSS.",
  "analyzingButton": "Analizando interfaz…",
  "retry": "Reintentar análisis",
  "reanalyze": "Volver a analizar",
  "analyze": "Activar generador",
  "cancelAnalysis": "Cancelar análisis",
  "analysisHelp": "Analiza la captura y después abre el código generado en el espacio de trabajo.",
  "analysisIdle": "Selecciona una captura para empezar.",
  "analysisReady": "Captura preparada para analizar.",
  "analysisBusy": "Analizando tu interfaz. Puede tardar hasta dos minutos.",
  "analysisSuccess": "Interfaz analizada correctamente.",
  "generate": "Generar y abrir código",
  "htmlSoon": "La generación HTML + CSS estará disponible próximamente.",
  "replaceProject": "Al generar de nuevo se reemplazan los cambios del proyecto de esta sesión.",
  "reference": "Referencia:",
  "screenshotEmpty": "Sin captura seleccionada",
  "screenshotDragging": "Suelta la imagen para validarla",
  "screenshotValidating": "Validando imagen…",
  "screenshotReady": "Captura lista",
  "screenshotError": "No se pudo aceptar la imagen",
  "screenshotEyebrow": "Entrada / Captura A",
  "screenshotTitle": "Imagen de referencia",
  "ready": "Lista",
  "empty": "Vacía",
  "dropTitle": "Arrastra tu interfaz aquí.",
  "dropHelp": "Selecciona una imagen de tu equipo o suéltala en este espacio.",
  "selectScreenshotLabel": "Seleccionar una captura de pantalla",
  "replaceScreenshot": "Reemplazar captura",
  "selectImage": "Seleccionar imagen",
  "removeScreenshot": "Eliminar captura",
  "cancelSelection": "Cancelar selección",
  "screenshotHelp": "PNG, JPEG o WEBP · Máximo {{size}}. Se enviará al servicio de análisis solo al activar la acción. No se guarda en el equipo.",
  "keepScreenshot": " Se conserva la captura anterior.",
  "selectedScreenshot": "Captura seleccionada: {{name}}",
  "file": "Archivo",
  "dimensions": "Dimensiones",
  "pixels": "píxeles",
  "size": "Tamaño",
  "format": "Formato",
  "editorLoadError": "No se pudo cargar el editor. Vuelve a abrir el espacio de código.",
  "editorEyebrow": "Estudio / Código",
  "editorTitle": "Espacio de código",
  "editorIntro": "Explora y ajusta tu interfaz. Los cambios duran solo esta sesión.",
  "projectMetadata": "React + Tailwind CSS · {{count}} archivos · Generador {{version}}",
  "editorLabel": "Editor de código",
  "activeFile": "Archivo activo",
  "noFile": "Ningún archivo seleccionado",
  "copy": "Copiar código",
  "reset": "Restaurar proyecto",
  "unsaved": "Cambios sin guardar en disco.",
  "originalCode": "Código original generado.",
  "editorLoading": "Cargando editor…",
  "editorAria": "Editor del archivo seleccionado",
  "generatedFiles": "Archivos generados",
  "filesEyebrow": "Proyecto / Archivos",
  "explorer": "Explorador",
  "noFiles": "No hay archivos disponibles.",
  "noProject": "Todavía no hay código generado. Analiza una captura para empezar.",
  "emptyProject": "Este proyecto no contiene archivos.",
  "selectFile": "Selecciona un archivo para ver su código.",
  "resetSuccess": "Se restauró el código original del proyecto.",
  "copySuccess": "Código copiado.",
  "copyFailure": "No se pudo copiar el código. Inténtalo de nuevo.",
  "analysisUnavailable": "El servicio de análisis no está disponible temporalmente. Inténtalo de nuevo.",
  "analysisLimited": "El servicio de análisis está temporalmente limitado. Inténtalo más tarde.",
  "analysisInvalid": "No se pudo interpretar correctamente la interfaz. Puedes volver a intentarlo.",
  "imageUnsupported": "El formato de la imagen no es compatible.",
  "imageLarge": "La imagen supera el tamaño máximo permitido.",
  "requestInvalid": "No se pudo enviar la captura. Revisa la imagen y vuelve a intentarlo.",
  "serviceMissing": "El servicio de análisis no está disponible en esta dirección.",
  "analysisFailure": "No se pudo completar el análisis. Inténtalo de nuevo.",
  "addressInvalid": "La dirección del servicio de análisis no es válida.",
  "responseInvalid": "El servicio devolvió una respuesta no válida. Inténtalo de nuevo.",
  "resultInvalid": "El servicio devolvió un análisis no válido. Inténtalo de nuevo.",
  "cancelled": "Análisis cancelado. Puedes volver a intentarlo.",
  "timeout": "El análisis tardó demasiado. Puedes volver a intentarlo.",
  "connectionFailure": "No se pudo conectar con el servicio de análisis. Comprueba la conexión e inténtalo de nuevo.",
  "decodeFailure": "No se pudo decodificar la imagen. Elige otro archivo.",
  "corruptImage": "No se pudo decodificar la imagen. Puede estar dañada; elige otro archivo.",
  "oneImage": "Selecciona una sola imagen a la vez.",
  "readFailure": "No se pudo leer la imagen. Intenta seleccionarla de nuevo.",
  "emptyImage": "El archivo está vacío. Selecciona una imagen válida.",
  "invalidFormat": "Formato no compatible. Selecciona una imagen PNG, JPEG o WEBP con su extensión correcta.",
  "invalidSignature": "El contenido del archivo no coincide con una imagen PNG, JPEG o WEBP válida.",
  "sizeLimit": "La imagen supera el límite de 10 MB. Selecciona un archivo más pequeño.",
  "theme": "Tema",
  "light": "Claro",
  "dark": "Oscuro",
  "preferences": "Preferencias de interfaz",
  "login": "Acceso",
  "loginEyebrow": "Acceso / Estación 01",
  "loginTitle": "Tu próxima interfaz empieza aquí.",
  "loginIntro": "Observa. Estructura. Construye.",
  "loginDescription": "Un laboratorio de interfaces: de una referencia visual a código que puedes explorar.",
  "email": "Correo electrónico",
  "password": "Contraseña",
  "showPassword": "Mostrar contraseña",
  "hidePassword": "Ocultar contraseña",
  "signIn": "Iniciar sesión",
  "createAccount": "Crear cuenta",
  "authUnavailable": "La autenticación todavía no está disponible. Estos campos son solo una muestra y no se envían ni se guardan.",
  "demoEntry": "Entrar a la demostración local",
  "demoLabel": "Modo de demostración · Sin autenticación",
  "loginScreen": "Ver pantalla de acceso",
  "labStatus": "Laboratorio de interfaces / Versión 0.1.0"
};
export const en: Record<keyof typeof es, string> = {
  "skip": "Skip to workspace",
  "navigation": "Main navigation",
  "brandLabel": "Vision2Code workspace",
  "capture": "Capture",
  "code": "Code",
  "projectsSoon": "Projects, coming soon",
  "projects": "Projects",
  "librarySoon": "Library, coming soon",
  "library": "Library",
  "footer": "Vision2Code / Interface studio",
  "version": "Version 0.1.0",
  "captureEyebrow": "Generator / Console 01",
  "captureTitle": "Capture console",
  "captureIntro": "From a visual reference to an interface structure.",
  "analysisBadge": "Interface analysis",
  "inputStage": "Input",
  "profileStage": "Profile",
  "analysisStage": "Analysis",
  "resultStage": "Result",
  "exportStage": "Export",
  "workflow": "Workflow stages",
  "soon": "Coming soon",
  "profileEyebrow": "Configuration panel",
  "profileTitle": "Generation profile",
  "outputStack": "Output technology",
  "noFramework": "No framework",
  "styles": "Styling",
  "language": "Language",
  "codeLanguage": "Language",
  "fidelity": "Visual fidelity",
  "structure": "Main structure",
  "structureHelp": "Layout, text and controls.",
  "instructions": "Instructions · Coming soon",
  "instructionsHelp": "Generation instructions will be available in a future release.",
  "profileHelp": "Analysis uses only your screenshot. Code generation is available for React + Tailwind CSS.",
  "analyzingButton": "Analyzing interface…",
  "retry": "Retry analysis",
  "reanalyze": "Analyze again",
  "analyze": "Start generator",
  "cancelAnalysis": "Cancel analysis",
  "analysisHelp": "Analyze the screenshot, then open the generated code in the workspace.",
  "analysisIdle": "Select a screenshot to get started.",
  "analysisReady": "Screenshot ready for analysis.",
  "analysisBusy": "Analyzing your interface. This can take up to two minutes.",
  "analysisSuccess": "Interface analyzed successfully.",
  "generate": "Generate and open code",
  "htmlSoon": "HTML + CSS generation is coming soon.",
  "replaceProject": "Generating again replaces project edits from this session.",
  "reference": "Reference:",
  "screenshotEmpty": "No screenshot selected",
  "screenshotDragging": "Drop the image to validate it",
  "screenshotValidating": "Validating image…",
  "screenshotReady": "Screenshot ready",
  "screenshotError": "The image could not be accepted",
  "screenshotEyebrow": "Input / Capture A",
  "screenshotTitle": "Reference image",
  "ready": "Ready",
  "empty": "Empty",
  "dropTitle": "Drop your interface here.",
  "dropHelp": "Choose an image from your computer or drop it here.",
  "selectScreenshotLabel": "Select a screenshot",
  "replaceScreenshot": "Replace screenshot",
  "selectImage": "Select image",
  "removeScreenshot": "Remove screenshot",
  "cancelSelection": "Cancel selection",
  "screenshotHelp": "PNG, JPEG or WEBP · Maximum {{size}}. Sent to the analysis service only when you start analysis. Not saved to disk.",
  "keepScreenshot": " The previous screenshot is retained.",
  "selectedScreenshot": "Selected screenshot: {{name}}",
  "file": "File",
  "dimensions": "Dimensions",
  "pixels": "pixels",
  "size": "Size",
  "format": "Format",
  "editorLoadError": "The editor could not load. Reopen the code workspace.",
  "editorEyebrow": "Studio / Code",
  "editorTitle": "Code workspace",
  "editorIntro": "Explore and adjust your interface. Changes last only for this session.",
  "projectMetadata": "React + Tailwind CSS · {{count}} files · Generator {{version}}",
  "editorLabel": "Code editor",
  "activeFile": "Active file",
  "noFile": "No file selected",
  "copy": "Copy code",
  "reset": "Reset project",
  "unsaved": "Changes are not saved to disk.",
  "originalCode": "Original generated code.",
  "editorLoading": "Loading editor…",
  "editorAria": "Selected file editor",
  "generatedFiles": "Generated files",
  "filesEyebrow": "Project / Files",
  "explorer": "Explorer",
  "noFiles": "No files available.",
  "noProject": "No generated code yet. Analyze a screenshot to get started.",
  "emptyProject": "This project contains no files.",
  "selectFile": "Select a file to view its code.",
  "resetSuccess": "Original project code restored.",
  "copySuccess": "Code copied.",
  "copyFailure": "Could not copy the code. Try again.",
  "analysisUnavailable": "The analysis service is temporarily unavailable. Try again.",
  "analysisLimited": "The analysis service is temporarily rate limited. Try again later.",
  "analysisInvalid": "The interface could not be interpreted. You can try again.",
  "imageUnsupported": "The image format is not supported.",
  "imageLarge": "The image exceeds the maximum allowed size.",
  "requestInvalid": "Could not send the screenshot. Check the image and try again.",
  "serviceMissing": "The analysis service is not available at this address.",
  "analysisFailure": "Could not complete the analysis. Try again.",
  "addressInvalid": "The analysis service address is invalid.",
  "responseInvalid": "The service returned an invalid response. Try again.",
  "resultInvalid": "The service returned an invalid analysis. Try again.",
  "cancelled": "Analysis cancelled. You can try again.",
  "timeout": "Analysis took too long. You can try again.",
  "connectionFailure": "Could not connect to the analysis service. Check your connection and try again.",
  "decodeFailure": "Could not decode the image. Choose another file.",
  "corruptImage": "Could not decode the image. It may be damaged; choose another file.",
  "oneImage": "Select one image at a time.",
  "readFailure": "Could not read the image. Try selecting it again.",
  "emptyImage": "The file is empty. Select a valid image.",
  "invalidFormat": "Unsupported format. Choose a PNG, JPEG or WEBP image with the correct extension.",
  "invalidSignature": "The file contents do not match a valid PNG, JPEG or WEBP image.",
  "sizeLimit": "The image exceeds the 10 MB limit. Select a smaller file.",
  "theme": "Theme",
  "light": "Light",
  "dark": "Dark",
  "preferences": "Interface preferences",
  "login": "Sign in",
  "loginEyebrow": "Access / Station 01",
  "loginTitle": "Your next interface starts here.",
  "loginIntro": "Observe. Structure. Build.",
  "loginDescription": "An interface laboratory: from a visual reference to code you can explore.",
  "email": "Email",
  "password": "Password",
  "showPassword": "Show password",
  "hidePassword": "Hide password",
  "signIn": "Sign in",
  "createAccount": "Create account",
  "authUnavailable": "Authentication is not available yet. These fields are a demonstration only and are neither sent nor saved.",
  "demoEntry": "Enter the local demo",
  "demoLabel": "Demo mode · No authentication",
  "loginScreen": "View sign-in screen",
  "labStatus": "Interface laboratory / Version 0.1.0"
};

// Compatibility boundary for messages produced by existing framework-independent models.
export const messageKeys: Record<string, keyof typeof es> = Object.fromEntries(
  Object.entries(es).map(([key, value]) => [value, key]),
) as Record<string, keyof typeof es>;
